package huffmanlzw;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class HuffmanLZWcompressor extends javax.swing.JDialog {
    
    private static double haffmanRatio,lzwRatio;
    
    private void setHaffmanRatio(double cmpr, double org){
        haffmanRatio = (double) cmpr /(double) org;
        huffmanVal.setText(String.format("%.3f", this.haffmanRatio));
    }
    private void setLZWRatio(double cmpr, double org){
        lzwRatio = (double) cmpr /(double) org;
        lzwVal.setText(String.format("%.3f", this.lzwRatio));
    }
    public HuffmanLZWcompressor(String filename) throws IOException {
        this.haffmanRatio = 0.0;
        this.lzwRatio =0.0;
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        setTitle("Compression ratios for: " + filename + "");
        runCompression(Paths.get(filename));
    }

    private void runCompression(Path wavFilePath) throws IOException {
        
        byte[] bytes = Files.readAllBytes(wavFilePath);
        int size = Byte.SIZE * bytes.length;
        int cmprSize;

        HuffmanCompressor haffman;
        
        haffman = new HuffmanCompressor(bytes);
        
        byte[] huffmanData = haffman.compress();
        cmprSize = Byte.SIZE * huffmanData.length;
        setHaffmanRatio(cmprSize,size);
        
        LZWCompessor lzw;
        lzw = new LZWCompessor(bytes);
        byte[] lzwData = lzw.compress();
        cmprSize = Byte.SIZE * lzwData.length;
        setLZWRatio(cmprSize,size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        huffmanLabel = new javax.swing.JLabel();
        lzwLabel = new javax.swing.JLabel();
        huffmanVal = new javax.swing.JLabel();
        lzwVal = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        titleLabel.setText("Q1: Huffman & LZW");

        huffmanLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        huffmanLabel.setText("Huffman coding compression ratio");

        lzwLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lzwLabel.setText("LZW coding compression ratio");

        huffmanVal.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        huffmanVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        huffmanVal.setText("[value]");

        lzwVal.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lzwVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lzwVal.setText("[value]");

        closeButton.setText("close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titleLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(huffmanVal)
                                .addComponent(lzwVal))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lzwLabel)
                                .addComponent(huffmanLabel)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huffmanVal)
                    .addComponent(huffmanLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lzwLabel)
                    .addComponent(lzwVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel huffmanLabel;
    private javax.swing.JLabel huffmanVal;
    private javax.swing.JLabel lzwLabel;
    private javax.swing.JLabel lzwVal;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
